import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetStaticProps } from "next";
import { getSortedPostsData } from "@/lib/post";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({
  allPostsData,
}: {
  allPostsData: {
    date: string;
    title: string;
    id: string;
  }[];
}) {
  // console.log(allPostsData);
  return (
    <>
      <Head>
        <title>NextJS Practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {allPostsData.map(({ id, title, date }) => (
          <li key={id} className={`${styles.li}`}>
            <Link href={`/posts/${id}`}>{title}</Link>
            <br /> <small>{date}</small>
          </li>
        ))}
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const allPostsData = getSortedPostsData();
  return {
    props: { allPostsData },
  };
};
